language: perl
perl:
  - blead
  - dev
#  No clean build due to removal of '.' from lib path
#  - 5.26
  - 5.24
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
#  stopping builds; is anyone really still using this version?
#  - 5.8
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
  allow_failures:
    - perl: blead
    - perl: blead-thr
sudo: false
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpanm -n -f Pod::Coverage::TrustPod Test::Perl::Critic
